services:
  - type: web
    name: tg-app-einstein-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          name: tg-app-einstein-backend
          type: web
          property: url
      - key: VITE_TELEGRAM_BOT_USERNAME
        sync: false 